sonar.projectKey=daviholandas_RiseOn.CatCar
sonar.organization=daviholandas
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/Migrations/**/*.cs,**/bin/**,**/obj/**
sonar.cpd.exclusions=**/Migrations/**/*.cs,**/*DbContext.cs,**/SnakeCaseConvention.cs
sonar.coverage.exclusions=**/Migrations/**/*.cs
