<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CatCar.Contexts.IdentityAccess</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="RiseOn.AutoInject" />
    <PackageReference Include="RiseOn.ResultRail" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\CatCar.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Contracts\CatCar.Contracts.csproj" />
  </ItemGroup>
</Project>