<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CatCar.Contexts.ServiceOperations</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="RiseOn.AutoInject" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\CatCar.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Contracts\CatCar.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\SharedInfrastructure\SnakeCaseNaming.cs" Link="Infrastructure\Persistence\SnakeCaseNaming.cs" />
  </ItemGroup>
</Project>