namespace CatCar.Contexts.ServiceOperations.Features.WorkOrders.GetWorkOrderAverageExecutionTime;

public sealed record WorkOrderAverageExecutionTime(int TotalCompletedWorkOrders, double AverageTotalExecutionTimeHours, double AverageDiagnosisTimeHours, double AverageExecutionTimeHours);
