<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>218a5135-37e5-4555-ac88-7b1bdd21cf15</UserSecretsId>
    <NoWarn>$(NoWarn);ASPIREPIPELINES003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\CatCar.Api.csproj" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
    <PackageReference Include="Aspire.Hosting.Azure.ContainerRegistry" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
    <PackageReference Include="Aspire.Hosting.Azure.OperationalInsights" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.Kubernetes" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

</Project>
