<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>CatCar.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\CatCar.Contracts.csproj" />
    <ProjectReference Include="..\Contexts\ServiceOperations\CatCar.Contexts.ServiceOperations.csproj" />
    <ProjectReference Include="..\Contexts\CatalogInventory\CatCar.Contexts.CatalogInventory.csproj" />
    <ProjectReference Include="..\Contexts\Communication\CatCar.Contexts.Communication.csproj" />
    <ProjectReference Include="..\Contexts\IdentityAccess\CatCar.Contexts.IdentityAccess.csproj" />
    <ProjectReference Include="..\Host\CatCar.ServiceDefaults\CatCar.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>