// <auto-generated />
using System;
using CatCar.Contexts.CatalogInventory.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CatCar.Contexts.CatalogInventory.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CatalogInventoryDbContext))]
[Migration("20260915200000_AddReservationUniqueness")]
public partial class AddReservationUniqueness : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<DateTime>(
            name: "created_at",
            schema: "catalog_inventory",
            table: "inventory_reservations",
            type: "timestamp with time zone",
            nullable: false,
            defaultValueSql: "CURRENT_TIMESTAMP");

        migrationBuilder.AddColumn<string>(
            name: "created_by",
            schema: "catalog_inventory",
            table: "inventory_reservations",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            defaultValue: "system");

        migrationBuilder.AddColumn<DateTime>(
            name: "updated_at",
            schema: "catalog_inventory",
            table: "inventory_reservations",
            type: "timestamp with time zone",
            nullable: false,
            defaultValueSql: "CURRENT_TIMESTAMP");

        migrationBuilder.AddColumn<string>(
            name: "updated_by",
            schema: "catalog_inventory",
            table: "inventory_reservations",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            defaultValue: "system");

        migrationBuilder.CreateIndex(
            name: "IX_inventory_reservations_budget_id_inventory_item_id",
            schema: "catalog_inventory",
            table: "inventory_reservations",
            columns: new[] { "budget_id", "inventory_item_id" },
            unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "IX_inventory_reservations_budget_id_inventory_item_id",
            schema: "catalog_inventory",
            table: "inventory_reservations");

        migrationBuilder.DropColumn(
            name: "created_at",
            schema: "catalog_inventory",
            table: "inventory_reservations");

        migrationBuilder.DropColumn(
            name: "created_by",
            schema: "catalog_inventory",
            table: "inventory_reservations");

        migrationBuilder.DropColumn(
            name: "updated_at",
            schema: "catalog_inventory",
            table: "inventory_reservations");

        migrationBuilder.DropColumn(
            name: "updated_by",
            schema: "catalog_inventory",
            table: "inventory_reservations");
    }
}
