<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CatCar.Contexts.ServiceOperations.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Weasel.Postgresql" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Contexts\ServiceOperations\CatCar.Contexts.ServiceOperations.csproj" />
    <ProjectReference Include="..\..\..\src\Contracts\CatCar.Contracts.csproj" />
  </ItemGroup>
</Project>
