// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CatCar.Contexts.ServiceOperations.Infrastructure.Persistence.Migrations;

public partial class AddWorkOrderLifecycleTracking : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<DateTime>(
            name: "diagnosis_started_at",
            schema: "service_operations",
            table: "work_orders",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "budget_approved_at",
            schema: "service_operations",
            table: "work_orders",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "completed_at",
            schema: "service_operations",
            table: "work_orders",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "delivered_at",
            schema: "service_operations",
            table: "work_orders",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "last_updated_at",
            schema: "service_operations",
            table: "work_orders",
            type: "timestamp with time zone",
            nullable: false,
            defaultValueSql: "CURRENT_TIMESTAMP");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(name: "diagnosis_started_at", schema: "service_operations", table: "work_orders");
        migrationBuilder.DropColumn(name: "budget_approved_at", schema: "service_operations", table: "work_orders");
        migrationBuilder.DropColumn(name: "completed_at", schema: "service_operations", table: "work_orders");
        migrationBuilder.DropColumn(name: "delivered_at", schema: "service_operations", table: "work_orders");
        migrationBuilder.DropColumn(name: "last_updated_at", schema: "service_operations", table: "work_orders");
    }
}
